// File generated by FlutterFire CLI / Antigravity Firebase Assistant.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubzcYrOL3LKI7Umh103KBfG4sErZ8T3c',
    appId: '1:472022657503:web:4f16967efafb8c19a63c6a',
    messagingSenderId: '472022657503',
    projectId: 'tenkasi-dreams',
    authDomain: 'tenkasi-dreams.firebaseapp.com',
    storageBucket: 'tenkasi-dreams.firebasestorage.app',
    measurementId: 'G-MDTX84WDD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNP_ZzSOLgoaD5ft-78MTflyxsv9ONp-Q',
    appId: '1:472022657503:android:a8cff0e52efdb530a63c6a',
    messagingSenderId: '472022657503',
    projectId: 'tenkasi-dreams',
    storageBucket: 'tenkasi-dreams.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDubzcYrOL3LKI7Umh103KBfG4sErZ8T3c',
    appId: '1:472022657503:ios:4f16967efafb8c19a63c6a',
    messagingSenderId: '472022657503',
    projectId: 'tenkasi-dreams',
    storageBucket: 'tenkasi-dreams.firebasestorage.app',
  );
}
