<?php
/**
 * Tenkasi Dreams Land - Database & JSON Property Seeder
 * Populates rich, realistic Tenkasi real estate listings across all categories:
 * House, Land, Farmland, Shop, Rental, Apartment.
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');

require_once __DIR__ . '/config.php';

$pdo = getDbConnection();

$seedProperties = [
    [
        'id' => 'prop_house_tenkasi_01',
        'title' => '3 BHK தனி சொகுசு வீடு - 1800 Sq.Ft, புதிய பேருந்து நிலையம் அருகில், தென்காசி',
        'description' => 'தென்காசி புதிய பேருந்து நிலையம் அருகில் 1800 சதுர அடியில் அமைந்துள்ள அழகிய 3 BHK தனி வீடு. DTCP அங்கீகாரம் பெற்றது. 24 மணி நேர குடிநீர் வசதி மற்றும் போர்வெல் உள்ளது. வங்கி கடன் வசதி உண்டு.',
        'price' => 4800000,
        'location' => 'புதிய பேருந்து நிலையம் அருகில், தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'House',
        'areaSqFt' => 1800,
        'superBuiltUpSqFt' => 1800,
        'carpetAreaSqFt' => 1550,
        'bedrooms' => 3,
        'bathrooms' => 3,
        'furnishingStatus' => 'Semi-Furnished',
        'facing' => 'East',
        'floor' => 'Ground + 1st Floor',
        'posterType' => 'Direct Owner',
        'landUnit' => 'Cent',
        'landUnitValue' => 4.13,
        'approvalType' => 'DTCP Approved',
        'isBankLoanAvailable' => true,
        'isPriceNegotiable' => true,
        'waterSource' => 'Both',
        'hasLift' => false,
        'hasTrees' => false,
        'isLease' => false,
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'முருகன் (உரிமையாளர்)',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['house_1'],
        'imageUrls' => [],
        'amenities' => ['24x7 Water Supply', 'Covered Car Parking', 'Borewell', 'Compound Wall', 'Vastu Compliant'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isFeatured' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 142,
        'enquiries' => 18,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-1 day'))
    ],
    [
        'id' => 'prop_house_ilanji_02',
        'title' => '2 BHK தனி வீடு - 1200 Sq.Ft, குற்றாலம் மெயின் ரோடு, இலஞ்சி',
        'description' => 'குற்றாலம் பிரதான சாலையில் இலஞ்சியில் அமைந்துள்ள நவீன 2 BHK வீடு. அமைதியான குடியிருப்பு பகுதி. சுத்தமான காற்று மற்றும் மூலிகை நீர் வளம்.',
        'price' => 3500000,
        'location' => 'குற்றாலம் மெயின் ரோடு, இலஞ்சி, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'House',
        'areaSqFt' => 1200,
        'superBuiltUpSqFt' => 1200,
        'carpetAreaSqFt' => 1050,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'furnishingStatus' => 'Unfurnished',
        'facing' => 'North',
        'floor' => 'Ground Floor',
        'posterType' => 'Direct Owner',
        'landUnit' => 'Cent',
        'landUnitValue' => 3.0,
        'approvalType' => 'Panchayat Approved',
        'isBankLoanAvailable' => true,
        'isPriceNegotiable' => true,
        'waterSource' => 'Both',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'சுரேஷ் குமார்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['house_2'],
        'imageUrls' => [],
        'amenities' => ['Car Parking', 'Borewell', 'Garden Space'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isFeatured' => false,
        'isPremium' => true,
        'isUserPosted' => false,
        'views' => 89,
        'enquiries' => 12,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-2 days'))
    ],
    [
        'id' => 'prop_house_pavoor_03',
        'title' => '4 BHK பிரம்மாண்ட தனி பங்களா - 2500 Sq.Ft, பாவூர்சத்திரம்',
        'description' => 'பாவூர்சத்திரம் மெயின் ரோட்டில் அமைந்துள்ள 4 BHK நவீன சொகுசு பங்களா. காம்பவுண்ட் சுவர், கார் பார்க்கிங், சிசிடிவி கேமரா வசதியுடன்.',
        'price' => 6800000,
        'location' => 'மெயின் ரோடு, பாவூர்சத்திரம், தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'House',
        'areaSqFt' => 2500,
        'superBuiltUpSqFt' => 2500,
        'carpetAreaSqFt' => 2200,
        'bedrooms' => 4,
        'bathrooms' => 4,
        'furnishingStatus' => 'Semi-Furnished',
        'facing' => 'East',
        'floor' => 'G + 1',
        'posterType' => 'Direct Owner',
        'landUnit' => 'Cent',
        'landUnitValue' => 5.5,
        'approvalType' => 'DTCP Approved',
        'isBankLoanAvailable' => true,
        'isPriceNegotiable' => true,
        'waterSource' => 'Both',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'மகேந்திரன்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['house_1'],
        'imageUrls' => [],
        'amenities' => ['CCTV Surveillance', '24x7 Security', 'Covered Parking', 'Solar Water Heater'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isFeatured' => false,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 210,
        'enquiries' => 24,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-3 days'))
    ],
    [
        'id' => 'prop_land_bypass_01',
        'title' => 'DTCP அப்ரூவ்டு வீட்டு மனை - 1200 Sq.Ft (2.75 சென்ட்), தென்காசி பைபாஸ்',
        'description' => 'தென்காசி பைபாஸ் சாலையில் அமைந்துள்ள DTCP & RERA அங்கீகரிக்கப்பட்ட வீட்டு மனை. 30 அடி தார் சாலை, மின்சாரம், குடிநீர் இணைப்பு வசதிகள் உடனடியாக கிடைக்கும்.',
        'price' => 1650000,
        'location' => 'பைபாஸ் ரோடு, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Land',
        'areaSqFt' => 1200,
        'landUnit' => 'Cent',
        'landUnitValue' => 2.75,
        'approvalType' => 'DTCP Approved',
        'facing' => 'South',
        'posterType' => 'Direct Owner',
        'isBankLoanAvailable' => true,
        'isPriceNegotiable' => true,
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'ஆனந்த் ராஜ்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['land_1'],
        'imageUrls' => [],
        'amenities' => ['30 Feet Tar Road', 'EB Line', 'Street Lights', 'Immediate Construction'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isFeatured' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 312,
        'enquiries' => 45,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-1 day'))
    ],
    [
        'id' => 'prop_land_surandai_02',
        'title' => 'விலை குறைந்த வீட்டு மனை - 1500 Sq.Ft, சுரண்டை மெயின் ரோடு',
        'description' => 'சுரண்டை பிரதான சாலைக்கு மிக அருகில் உள்ள முதலீட்டிற்கு ஏற்ற வீட்டு மனை. எதிர்காலத்தில் அதிக லாபம் தரும் பகுதி.',
        'price' => 1050000,
        'location' => 'சுரண்டை மெயின் ரோடு, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Land',
        'areaSqFt' => 1500,
        'landUnit' => 'Cent',
        'landUnitValue' => 3.44,
        'approvalType' => 'Panchayat Approved',
        'facing' => 'East',
        'posterType' => 'Direct Owner',
        'isBankLoanAvailable' => false,
        'isPriceNegotiable' => true,
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'கணேசன்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['land_2'],
        'imageUrls' => [],
        'amenities' => ['Good Groundwater', 'Near Bus Stop'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => true,
        'isUserPosted' => false,
        'views' => 156,
        'enquiries' => 19,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-4 days'))
    ],
    [
        'id' => 'prop_land_kadayanallur_03',
        'title' => 'கமர்ஷியல் நிலம் - 2400 Sq.Ft (5.5 சென்ட்), கடையநல்லூர் ரோடு',
        'description' => 'பிரதான சாலையில் அமைந்துள்ள வணிக பயன்பாட்டிற்கு உகந்த நிலம். ஷாப்பிங் காம்ப்ளக்ஸ், மருத்துவமனை, அல்லது குடோன் அமைக்க மிகச் சிறந்தது.',
        'price' => 3800000,
        'location' => 'கடையநல்லூர் மெயின் ரோடு, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Land',
        'areaSqFt' => 2400,
        'landUnit' => 'Cent',
        'landUnitValue' => 5.5,
        'approvalType' => 'DTCP Approved',
        'facing' => 'North',
        'posterType' => 'Direct Owner',
        'isBankLoanAvailable' => true,
        'isPriceNegotiable' => true,
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'ரஹ்மான்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['land_1'],
        'imageUrls' => [],
        'amenities' => ['Main Road Facing', 'Heavy Vehicle Access', 'Commercial Zone'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 180,
        'enquiries' => 22,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-5 days'))
    ],
    [
        'id' => 'prop_farm_mathalamparai_01',
        'title' => '3 ஏக்கர் செழிப்பான தென்னந்தோப்பு - 250 காய்க்கும் மரங்கள், இலவச EB, மத்தளம்பாறை',
        'description' => 'தென்காசி மத்தளம்பாறையில் அமைந்துள்ள 3 ஏக்கர் பசுமையான தென்னந்தோப்பு. 250 நன்கு காய்க்கும் தென்னை மரங்கள், 5 HP இலவச விவசாய மின் இணைப்பு, ஆழ்துளை கிணறு, சொட்டு நீர் பாசனம். மாதம் ₹60,000 வருமானம்.',
        'price' => 8500000,
        'location' => 'மத்தளம்பாறை, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Farmland',
        'areaSqFt' => 130680,
        'landUnit' => 'Acre',
        'landUnitValue' => 3.0,
        'hasTrees' => true,
        'treesDetails' => '250 தென்னை மரங்கள், 15 மாமரங்கள், 10 பலா மரங்கள்',
        'hasIncome' => true,
        'incomeDetails' => 'மாதம் ₹60,000 தேங்காய் மகசூல் வருமானம்',
        'waterSource' => 'Borewell + Canal',
        'powerPhase' => 'Three Phase (Free Agri EB)',
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'சண்முகநாதன்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['farm_1'],
        'imageUrls' => [],
        'amenities' => ['Free Agri Electricity', 'Drip Irrigation', 'Borewell with 5HP Motor', 'Fenced Boundary'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isFeatured' => true,
        'isPremium' => true,
        'isUserPosted' => false,
        'views' => 420,
        'enquiries' => 58,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-1 day'))
    ],
    [
        'id' => 'prop_farm_courtallam_02',
        'title' => '1.5 ஏக்கர் மாந்தோப்பு & பண்ணை வீடு - குற்றாலம் அடிவாரம்',
        'description' => 'குற்றாலம் மலை அடிவாரத்தில் இயற்கை எழில் கொஞ்சும் 1.5 ஏக்கர் மாந்தோப்பு. அழகிய சிறிய பண்னை வீடு, போர்வெல், வேலி அமைக்கப்பட்டுள்ளது. ஓய்வு விடுதி (Resort) அமைக்க உகந்தது.',
        'price' => 5500000,
        'location' => 'குற்றாலம் அடிவாரம், தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Farmland',
        'areaSqFt' => 65340,
        'landUnit' => 'Acre',
        'landUnitValue' => 1.5,
        'hasTrees' => true,
        'treesDetails' => '100 அல்போன்சா மாமரங்கள்',
        'waterSource' => 'Mountain Stream + Bore',
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'பாலசுப்பிரமணியன்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['farm_2'],
        'imageUrls' => [],
        'amenities' => ['Farmhouse Structure', 'Mountain View', 'Natural Stream Water'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 290,
        'enquiries' => 34,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-6 days'))
    ],
    [
        'id' => 'prop_farm_sengottai_03',
        'title' => '75 சென்ட் விவசாய நிலம் - வற்றாத கிணற்று பாசனம், செங்கோட்டை',
        'description' => 'செங்கோட்டை புளியரை சாலையில் அமைந்துள்ள 75 சென்ட் செழிப்பான நன்செய் நிலம். நெல், வாழை பயிரிட மிகச் சிறந்தது.',
        'price' => 2600000,
        'location' => 'செங்கோட்டை, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Farmland',
        'areaSqFt' => 32670,
        'landUnit' => 'Cent',
        'landUnitValue' => 75.0,
        'waterSource' => 'Well Water',
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'முத்தையா',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['farm_1'],
        'imageUrls' => [],
        'amenities' => ['Open Well with Abundant Water', 'All Weather Road Access'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 115,
        'enquiries' => 14,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-7 days'))
    ],
    [
        'id' => 'prop_shop_market_01',
        'title' => 'வணிக கடை விற்பனைக்கு - 450 Sq.Ft, தென்காசி மார்க்கெட் ரோடு',
        'description' => 'தென்காசி பழைய மார்க்கெட் மெயின் ரோட்டில் அமைந்துள்ள 450 Sq.Ft வணிக கடை. ரோலிங் ஷட்டர், 3-பேஸ் மின்சாரம், டைல்ஸ் தரைத்தளம் உள்ளது. மாதம் ₹20,000 வாடகை வருமானம் உறுதி.',
        'price' => 2500000,
        'location' => 'மார்க்கெட் ரோடு, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Shop',
        'areaSqFt' => 450,
        'hasShutter' => true,
        'powerPhase' => 'Three Phase',
        'hasWaterSupply' => true,
        'commercialAreaType' => 'Retail Shop / Office',
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'அப்துல் காதர்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['shop_1'],
        'imageUrls' => [],
        'amenities' => ['Rolling Shutter', 'Three Phase Power', 'Drinking Water', 'Prime Commercial Area'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => true,
        'isUserPosted' => false,
        'views' => 198,
        'enquiries' => 26,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-2 days'))
    ],
    [
        'id' => 'prop_shop_complex_02',
        'title' => 'இரு அடுக்கு வணிக வளாகம் - 2000 Sq.Ft, புதிய பேருந்து நிலையம் ரோடு',
        'description' => 'புதிய பேருந்து நிலைய மெயின் ரோட்டில் அமைந்துள்ள இரு அடுக்கு வணிக வளாகம் (G+1). கீழ்தளம் 2 கடைகள், மேல்தளம் அலுவலகம். மாதம் ₹45,000 வாடகை கிடைத்து வருகிறது.',
        'price' => 9500000,
        'location' => 'புதிய பேருந்து நிலையம் ரோடு, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Shop',
        'areaSqFt' => 2000,
        'hasShutter' => true,
        'powerPhase' => 'Three Phase',
        'commercialAreaType' => 'Commercial Complex',
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'ராஜேந்திரன்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['shop_2'],
        'imageUrls' => [],
        'amenities' => ['High Rental Yield', '3-Phase EB', 'Parking Space', 'Corner Property'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isFeatured' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 340,
        'enquiries' => 42,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-3 days'))
    ],
    [
        'id' => 'prop_apt_town_01',
        'title' => '2 BHK புதிய அடுக்குமாடி குடியிருப்பு - 980 Sq.Ft, லிப்ட் & பார்க்கிங், தென்காசி',
        'description' => 'தென்காசி நகரில் பிரதான பகுதியில் அமைந்துள்ள பிரீமியம் 2 BHK அபார்ட்மெண்ட். லிப்ட் வசதி, மூடப்பட்ட கார் பார்க்கிங், 24x7 செக்யூரிட்டி, பவர் பேக்கப் வசதிகள் உண்டு.',
        'price' => 3200000,
        'location' => 'டவுன் சென்டர், தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Apartment',
        'areaSqFt' => 980,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'hasLift' => true,
        'facing' => 'East',
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'கார்த்திகேயன்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['apt_1'],
        'imageUrls' => [],
        'amenities' => ['Passenger Lift', 'Covered Car Parking', '24x7 Power Backup', 'Security Guard'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 165,
        'enquiries' => 20,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-2 days'))
    ],
    [
        'id' => 'prop_rental_railway_01',
        'title' => '2 BHK வீடு வாடகைக்கு - 1000 Sq.Ft, தென்காசி ரயில்வே ஸ்டேஷன் அருகில்',
        'description' => 'தென்காசி ரயில்வே ஸ்டேஷன் அருகில் முதல் தளத்தில் உள்ள 2 BHK தனி வீடு வாடகைக்கு. குடும்பத்தினருக்கு மட்டும். 24 மணி நேர குடிநீர் வசதி உண்டு.',
        'price' => 9000,
        'location' => 'ரயில்வே ஸ்டேஷன் ரோடு, தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Rental',
        'isRental' => true,
        'rentalSubType' => 'Family House Rental',
        'advanceAmount' => 50000,
        'areaSqFt' => 1000,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'செல்வராஜ்',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['rental_1'],
        'imageUrls' => [],
        'amenities' => ['24 Hours Water', 'Two Wheeler Parking', 'Balcony'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => true,
        'isUserPosted' => false,
        'views' => 280,
        'enquiries' => 38,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-1 day'))
    ],
    [
        'id' => 'prop_rental_shop_02',
        'title' => 'வணிக கடை வாடகைக்கு - 350 Sq.Ft, மெயின் பஜார், தென்காசி',
        'description' => 'தென்காசி மெயின் பஜாரில் மக்கள் நடமாட்டம் மிகுந்த பகுதியில் அமைந்துள்ள கடை வாடகைக்கு. துணிக்கடை, மொபைல் ஷாப், கிளினிக் வைக்க ஏற்ற இடம்.',
        'price' => 14000,
        'location' => 'மெயின் பஜார், தென்காசி',
        'city' => 'Tenkasi',
        'propertyType' => 'Rental',
        'isRental' => true,
        'rentalSubType' => 'Commercial Shop Rental',
        'advanceAmount' => 100000,
        'areaSqFt' => 350,
        'hasShutter' => true,
        'posterType' => 'Direct Owner',
        'contactPhone' => '+91 98941 74944',
        'sellerName' => 'வேலுச்சாமி',
        'sellerPhone' => '+91 98941 74944',
        'imageKeys' => ['shop_1'],
        'imageUrls' => [],
        'amenities' => ['Main Bazaar Frontage', 'Rolling Shutter', 'Heavy Footfall'],
        'status' => 'active',
        'isFavorite' => false,
        'isVerified' => true,
        'isPremium' => false,
        'isUserPosted' => false,
        'views' => 195,
        'enquiries' => 27,
        'postedDate' => date('Y-m-d H:i:s', strtotime('-4 days'))
    ]
];

$savedToDb = 0;
$dbErrors = [];

function saveSeedPropertyToDb($p, $pdo) {
    $agent = $p['agent'] ?? [];
    $sql = "INSERT INTO `properties` 
        (`id`, `title`, `description`, `price`, `location`, `city`, `propertyType`, `areaSqFt`, `superBuiltUpSqFt`, `carpetAreaSqFt`, `bedrooms`, `bathrooms`, `furnishingStatus`, `facing`, `floor`, `maintenanceMonthly`, `landmark`, `posterType`, `landUnit`, `landUnitValue`, `landFeatures`, `approvalType`, `isBankLoanAvailable`, `isPriceNegotiable`, `waterSource`, `hasLift`, `hasTrees`, `treesDetails`, `hasIncome`, `incomeDetails`, `isLease`, `rentalSubType`, `advanceAmount`, `commercialAreaType`, `hasTable`, `hasFan`, `hasWaterSupply`, `hasShutter`, `powerPhase`, `contactPhone`, `sellerName`, `sellerPhone`, `imageKeys`, `imageUrls`, `amenities`, `agent_id`, `agent_name`, `agent_agencyName`, `agent_phone`, `agent_email`, `postedDate`, `status`, `isFavorite`, `isVerified`, `isFeatured`, `isUserPosted`, `isPremium`, `views`, `enquiries`)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE 
            `title`=VALUES(`title`), `description`=VALUES(`description`), `price`=VALUES(`price`),
            `location`=VALUES(`location`), `status`=VALUES(`status`), `isVerified`=VALUES(`isVerified`),
            `isFeatured`=VALUES(`isFeatured`), `isPremium`=VALUES(`isPremium`), `views`=VALUES(`views`), `enquiries`=VALUES(`enquiries`)";
    
    $stmt = $pdo->prepare($sql);
    return $stmt->execute([
        $p['id'],
        $p['title'] ?? '',
        $p['description'] ?? '',
        $p['price'] ?? 0,
        $p['location'] ?? 'Tenkasi',
        $p['city'] ?? 'Tenkasi',
        $p['propertyType'] ?? 'Land',
        $p['areaSqFt'] ?? 0,
        $p['superBuiltUpSqFt'] ?? null,
        $p['carpetAreaSqFt'] ?? null,
        $p['bedrooms'] ?? null,
        $p['bathrooms'] ?? null,
        $p['furnishingStatus'] ?? 'Unfurnished',
        $p['facing'] ?? 'East',
        $p['floor'] ?? 'Ground Floor',
        $p['maintenanceMonthly'] ?? null,
        $p['landmark'] ?? null,
        $p['posterType'] ?? 'Direct Owner',
        $p['landUnit'] ?? null,
        $p['landUnitValue'] ?? null,
        json_encode($p['landFeatures'] ?? [], JSON_UNESCAPED_UNICODE),
        $p['approvalType'] ?? null,
        !empty($p['isBankLoanAvailable']) ? 1 : 0,
        isset($p['isPriceNegotiable']) ? ($p['isPriceNegotiable'] ? 1 : 0) : 1,
        $p['waterSource'] ?? 'Both',
        !empty($p['hasLift']) ? 1 : 0,
        !empty($p['hasTrees']) ? 1 : 0,
        $p['treesDetails'] ?? null,
        !empty($p['hasIncome']) ? 1 : 0,
        $p['incomeDetails'] ?? null,
        !empty($p['isLease']) ? 1 : 0,
        $p['rentalSubType'] ?? null,
        $p['advanceAmount'] ?? null,
        $p['commercialAreaType'] ?? null,
        !empty($p['hasTable']) ? 1 : 0,
        !empty($p['hasFan']) ? 1 : 0,
        !empty($p['hasWaterSupply']) ? 1 : 0,
        !empty($p['hasShutter']) ? 1 : 0,
        $p['powerPhase'] ?? null,
        $p['contactPhone'] ?? '+91 98941 74944',
        $p['sellerName'] ?? 'Direct Owner',
        $p['sellerPhone'] ?? '+91 98941 74944',
        json_encode($p['imageKeys'] ?? [], JSON_UNESCAPED_UNICODE),
        json_encode($p['imageUrls'] ?? [], JSON_UNESCAPED_UNICODE),
        json_encode($p['amenities'] ?? [], JSON_UNESCAPED_UNICODE),
        $agent['id'] ?? 'admin_agent',
        $agent['name'] ?? $p['sellerName'] ?? 'Direct Owner',
        $agent['agencyName'] ?? 'நேரடி உரிமையாளர் (Direct Owner)',
        $agent['phone'] ?? $p['sellerPhone'] ?? '+91 98941 74944',
        $agent['email'] ?? 'tenkasidreams@gmail.com',
        $p['postedDate'] ?? date('Y-m-d H:i:s'),
        $p['status'] ?? 'active',
        !empty($p['isFavorite']) ? 1 : 0,
        isset($p['isVerified']) ? ($p['isVerified'] ? 1 : 0) : 1,
        !empty($p['isFeatured']) ? 1 : 0,
        !empty($p['isUserPosted']) ? 1 : 0,
        !empty($p['isPremium']) ? 1 : 0,
        $p['views'] ?? 0,
        $p['enquiries'] ?? 0
    ]);
}

if ($pdo) {
    foreach ($seedProperties as $p) {
        try {
            $ok = saveSeedPropertyToDb($p, $pdo);
            if ($ok) $savedToDb++;
        } catch (Exception $e) {
            $dbErrors[] = $p['id'] . ': ' . $e->getMessage();
        }
    }
} else {
    $dbErrors[] = 'Database connection is null (falling back to JSON)';
}

// Also write to properties.json for backup and fallback
$existingJson = readJsonStorage('properties.json');
if (!is_array($existingJson)) $existingJson = [];

// Index existing by id
$merged = [];
foreach ($existingJson as $item) {
    if (!empty($item['id'])) {
        $merged[$item['id']] = $item;
    }
}
foreach ($seedProperties as $item) {
    $merged[$item['id']] = $item;
}
$finalList = array_values($merged);
writeJsonStorage('properties.json', $finalList);

echo json_encode([
    'success' => true,
    'message' => 'Successfully seeded Tenkasi properties into database & JSON!',
    'saved_to_db' => $savedToDb,
    'total_json_properties' => count($finalList),
    'categories' => [
        'House' => 3,
        'Land' => 3,
        'Farmland' => 3,
        'Shop' => 2,
        'Apartment' => 1,
        'Rental' => 2
    ],
    'db_errors' => $dbErrors
], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
